particle_filter:
  ros__parameters:
    num_particles: 100

    # The number of lidar beams emitted from
    # each particle. This doesn't need to be
    # equal to the actual number (>1000)
    # so long as you downsample properly
    num_beams_per_particle: 99

    # The field of view centered around theta=0
    scan_field_of_view: 4.71 # radians
    
    # angle stride for downsampling the lidar data
    angle_step: 11

    # Discretize the theta space for faster ray tracing
    scan_theta_discretization: 500.0

    # The names of topics to listen and publish to
    map_topic: "/map"
    scan_topic: "/scan"
    odom_topic: "/vesc/odom"

    # The frame you should publish your transform to
    particle_filter_frame: "/base_link"

    # Deterministic flag; set to true to remove all added noise
    deterministic: false

    lidar_scale_to_map_scale: 1.0
